---
github: HafiziRuslan
patreon:
open_collective: hafiziruslan
ko_fi: hafiziruslan
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: hafiziruslan
thanks_dev: gh/hafiziruslan
custom: [https://paypal.me/HafiziRuslan]
