settings:
  # username: "Readme-Workflows" # Replace with your username or comment out this line
  commit_msg: 'Update activity'
  max_lines: 30
  # readme_file: "./TEMPLATE.md"
  disabled_events:
    - 'comments'
    - 'push'
  url_text: '{REPO}{ID}'
  date:
    timezone: 'Asia/Kuala_Lumpur'
    text: 'Activity updated: {DATE}'
    format: 'isoDateTime'
  # commit_name: "readme-bot"
  # commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
  line_prefix: '{NUM}. '
  ignored_repos:
    - HafiziRuslan/HafiziRuslan
messages:
  comments: '💬 Commented on {ID} in {REPO}'
  push: '⬆️ Pushed commit to {REPO}'
  issue_opened: '❗️ Opened issue {ID} in {REPO}'
  issue_closed: '✔️ Closed issue {ID} in {REPO}'
  pr_opened: '💪 Opened PR {ID} in {REPO}'
  pr_closed: '❌ Closed PR {ID} in {REPO}'
  pr_merged: '🎉 Merged PR {ID} in {REPO}'
  create_repo: '📔 Created {REPO}'
  fork_repo: '🔱 Forked {FORK} from {REPO}'
  wiki_create: '📖 Created new {WIKI} page in {REPO}'
  added_member: '🤝 Became collaborator on {REPO}'
  changes_approved: '👍 Approved changes in {ID} in {REPO}'
  changes_requested: '🔴 Requested changes in {ID} in {REPO}'
  new_release: '✌️ Released {ID} in {REPO}'
  new_star: '⭐ Starred {REPO}'
