name: activity

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: TheDanniCraft/activity-log@master
        with:
          GITHUB_USERNAME: ${{ github.repository_owner}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          EVENT_LIMIT: 30
          COMMIT_MESSAGE: 'Update activity'
