---
name: activities

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Kuala_Lumpur

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Generate the activity log
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://github.com/HafiziRuslan.atom,https://gitlab.com/hafiziruslan.atom,https://codeberg.org/hafiziruslan.rss,https://gist.github.com/HafiziRuslan.atom'
          feed_names: 'GitHub,GitLab,Codeberg,Gist'
          template: '$counter. $date > $feedName > [$title]($url)$newline'
          tag_post_pre_newline: true
          date_format: 'isoDateTime'
          max_post_count: 50
          gh_token: ${{ secrets.GH_TOKEN }}
          commit_message: 'activities'
          committer_username: 'github-actions[bot]'
          committer_email: '30207509+github-actions[bot]@users.noreply.github.com'
          remove_duplicates: true
