---
name: cards

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Kuala_Lumpur

permissions:
  contents: write

jobs:
  cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: stats card
        uses: readme-tools/github-readme-stats-action@main
        with:
          card: stats
          options: |
            {
              "username": "${{ github.repository_owner }}",
              "hide": "stars",
              "show": "prs_merged_percentage",
              "show_icons": true,
              "theme": "github_dark_dimmed",
              "hide_border": true,
              "rank_icon": "github",
              "include_all_commits": true,
              "card_width": 480
            }
          path: images/stats.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: langs card
        uses: readme-tools/github-readme-stats-action@main
        with:
          card: top-langs
          options: |
            {
              "username": "${{ github.repository_owner }}",
              "layout": "compact",
              "size_weight": 0.8,
              "count_weight": 0.2,
              "langs_count": 9,
              "stats_format": "bytes",
              "theme": "github_dark_dimmed",
              "hide_border": true,
              "card_width": 480
            }
          path: images/langs.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: time card
        uses: readme-tools/github-readme-stats-action@main
        with:
          card: wakatime
          options: |
            {
              "username": "${{ github.repository_owner }}",
              "hide_progress": true,
              "theme": "github_dark_dimmed",
              "hide_border": true,
              "custom_title": "Time Stats",
              "layout": "compact",
              "card_width": 480
            }
          path: images/time.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "30207509+github-actions[bot]@users.noreply.github.com"
          git add images/*.svg
          git commit -m "cards" || exit 0
          git push
