---
name: gh-activity

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Generate the activity log
        uses: TheDanniCraft/activity-log@master
        with:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          EVENT_LIMIT: 25
          HIDE_DETAILS_ON_PRIVATE_REPOS: true
          COMMIT_MESSAGE: 'gh-activity'
