---
name: lint

on:
  push:
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          FIX_MARKDOWN: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_YAML_PRETTIER: true
          VALIDATE_CHECKOV: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
