---
name: push

permissions:
  contents: read

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  codeberg:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          # sparse-checkout: |
          #   assets
          #   images

      - name: 'push to Codeberg'
        uses: cssnr/mirror-repository-action@master
        with:
          host: https://codeberg.org
          owner: hafiziruslan
          repo: .profile
          create: true
          username: hafiziruslan
          password: ${{ secrets.CODEBERG_TOKEN }}
          summary: false
          private: false

  gitlab:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          # sparse-checkout: |
          #   assets
          #   images

      - name: 'push to GitLab'
        uses: cssnr/mirror-repository-action@master
        with:
          host: https://gitlab.com
          owner: hafiziruslan
          repo: hafiziruslan
          create: true
          username: hafiziruslan
          password: ${{ secrets.GITLAB_TOKEN }}
          summary: false
          private: false

  gitea:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          # sparse-checkout: |
          #   assets
          #   images

      - name: 'push to Gitea'
        uses: cssnr/mirror-repository-action@master
        with:
          host: https://gitea.com
          owner: hafiziruslan
          repo: .profile
          create: true
          username: hafiziruslan
          password: ${{ secrets.GITEA_TOKEN }}
          summary: false
          private: false

  w0chp:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          # sparse-checkout: |
          #   assets
          #   images

      - name: 'push to WPSD-Dev'
        uses: cssnr/mirror-repository-action@master
        with:
          host: https://repo.w0chp.net
          owner: 9w2lgx
          repo: .profile
          create: true
          username: 9w2lgx
          password: ${{ secrets.W0CHP_TOKEN }}
          summary: false
          private: false
